language: node_js

node_js:
  - "stable"

# Use container-based Travis infrastructure.
sudo: false

script:
  - npm install codecov -g
  - yarn run test-ci
  - yarn run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - codecov

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - "$HOME/.cache/yarn"
    - node_modules